server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml  
  
spring:
  application:
    name: microserviceCloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: duhang-microservicecloud
  company.name: duhang
  build.artifactId: $project.artifactId$
  build.version: $project.version$




